fix: fixed a failing CI pipeline
The `many--prevent-merge-commits.yaml` workflow does not work on push to main
as it is looking for a PR:

```
[NOTICE] Collecting token from input...
[INFO] Token collected.
[NOTICE] Instantiating an Octokit client using token...
[INFO] Octokit client is ready.
[NOTICE] Retrieving commits of PR #undefined...
Error: [ERROR] Not Found
```

Thus I renamed it to `pull--prevent-merge-commits.yaml`, and disabled it from
running on pushes to production branches.